import type { Project } from "@/db/schema";

export const demoProjects: Project[] = [
  {
    id: 1,
    source: "github",
    sourceId: "open-webui/open-webui",
    url: "https://github.com/open-webui/open-webui",
    name: "Open WebUI",
    description:
      "User-friendly AI interface supporting Ollama, OpenAI, and other LLM runners.",
    summaryEs:
      "Una interfaz de usuario elegante y completa para interactuar con modelos de lenguaje como Ollama y OpenAI. Perfecta para quien quiere tener su propio ChatGPT privado sin depender de servicios externos. Incluye gestión de conversaciones, RAG integrado, y soporte multiusuario.",
    categoryId: 1,
    tags: ["llm", "chatbot", "self-hosted", "ollama", "ia"],
    difficulty: "facil",
    interestScore: 92,
    trendingVelocity: 4500,
    stars: 58000,
    forks: 7200,
    lastCommit: new Date("2026-04-01"),
    language: "TypeScript",
    isOssAlternative: true,
    alternativeTo: "ChatGPT Plus",
    replicableWithCode: null,
    automatizableWithN8n: "Con Claude Code puedes montar un sistema que responda emails automáticamente conectándose a la API de Open WebUI, sin necesidad de herramientas como n8n o Zapier.",
    featuredImageUrl: null,
    thumbnailUrl: null,
    contentImages: [],
    status: "published",
    priority: "high",
    seoSlug: "open-webui-tu-chatgpt-privado",
    seoTitle: "Open WebUI: Tu propio ChatGPT privado y gratuito",
    seoDescription:
      "Descubre Open WebUI, la alternativa open source a ChatGPT que puedes instalar en tu servidor. Soporte para Ollama, OpenAI y más.",
    readmeContent: null,
    author: "open-webui",
    createdAt: new Date("2026-03-28"),
    updatedAt: new Date("2026-04-01"),
    publishedAt: new Date("2026-03-29"),
  },
  {
    id: 2,
    source: "github",
    sourceId: "n8n-io/n8n",
    url: "https://github.com/n8n-io/n8n",
    name: "n8n",
    description:
      "Fair-code workflow automation platform with native AI capabilities.",
    summaryEs:
      "La plataforma de automatización de workflows más potente del mundo open source. Con n8n puedes conectar cualquier servicio, API o base de datos en flujos visuales sin escribir código. Incluye nodos nativos de IA para integrar LLMs directamente en tus automatizaciones.",
    categoryId: 4,
    tags: ["automatización", "workflow", "nocode", "ia", "integraciones"],
    difficulty: "medio",
    interestScore: 88,
    trendingVelocity: 2100,
    stars: 52000,
    forks: 8400,
    lastCommit: new Date("2026-04-01"),
    language: "TypeScript",
    isOssAlternative: true,
    alternativeTo: "Zapier",
    replicableWithCode: null,
    automatizableWithN8n: null,
    featuredImageUrl: null,
    thumbnailUrl: null,
    contentImages: [],
    status: "published",
    priority: "high",
    seoSlug: "n8n-alternativa-gratuita-zapier",
    seoTitle: "n8n: La alternativa gratuita a Zapier que puedes self-hostear",
    seoDescription:
      "n8n es la plataforma de automatización open source más completa. Alternativa a Zapier con IA integrada y sin límites.",
    readmeContent: null,
    author: "n8n-io",
    createdAt: new Date("2026-03-25"),
    updatedAt: new Date("2026-04-01"),
    publishedAt: new Date("2026-03-26"),
  },
  {
    id: 3,
    source: "github",
    sourceId: "ollama/ollama",
    url: "https://github.com/ollama/ollama",
    name: "Ollama",
    description: "Get up and running with large language models locally.",
    summaryEs:
      "Ejecuta modelos de lenguaje como Llama 3, Mixtral o Phi directamente en tu ordenador sin necesidad de GPU en la nube. Ollama simplifica al máximo la instalación y gestión de LLMs locales. Un solo comando y tienes tu modelo funcionando.",
    categoryId: 1,
    tags: ["llm", "local", "privacidad", "ia", "modelos"],
    difficulty: "facil",
    interestScore: 95,
    trendingVelocity: 6200,
    stars: 120000,
    forks: 9800,
    lastCommit: new Date("2026-04-01"),
    language: "Go",
    isOssAlternative: true,
    alternativeTo: "OpenAI API",
    replicableWithCode: null,
    automatizableWithN8n: "Con Claude Code puedes crear scripts que usen Ollama como motor de IA local para procesar textos, clasificar documentos o generar resúmenes sin depender de APIs externas.",
    featuredImageUrl: null,
    thumbnailUrl: null,
    contentImages: [],
    status: "published",
    priority: "high",
    seoSlug: "ollama-ejecuta-llms-en-local",
    seoTitle: "Ollama: Ejecuta LLMs en tu ordenador con un solo comando",
    seoDescription:
      "Ollama permite ejecutar Llama 3, Mixtral y otros modelos de IA en local. Sin cloud, sin costes, total privacidad.",
    readmeContent: null,
    author: "ollama",
    createdAt: new Date("2026-03-20"),
    updatedAt: new Date("2026-04-01"),
    publishedAt: new Date("2026-03-21"),
  },
  {
    id: 4,
    source: "hackernews",
    sourceId: "hn-39201",
    url: "https://github.com/BerriAI/litellm",
    name: "LiteLLM",
    description:
      "Call 100+ LLM APIs in OpenAI format. Load balance, fallbacks, spend tracking.",
    summaryEs:
      "Un proxy universal para APIs de LLMs que te permite llamar a más de 100 proveedores (OpenAI, Anthropic, Cohere, local) usando el mismo formato. Perfecto para empresas que quieren flexibilidad entre proveedores sin cambiar código. Incluye balanceo de carga y control de gastos.",
    categoryId: 1,
    tags: ["llm", "api", "proxy", "devtools", "ia"],
    difficulty: "medio",
    interestScore: 81,
    trendingVelocity: 1800,
    stars: 18500,
    forks: 2100,
    lastCommit: new Date("2026-03-31"),
    language: "Python",
    isOssAlternative: true,
    alternativeTo: "OpenRouter",
    replicableWithCode: "Se puede crear un proxy LLM básico con Claude Code que redirija peticiones entre proveedores",
    automatizableWithN8n: null,
    featuredImageUrl: null,
    thumbnailUrl: null,
    contentImages: [],
    status: "published",
    priority: "high",
    seoSlug: "litellm-proxy-universal-llms",
    seoTitle: "LiteLLM: Un proxy para gobernar todas las APIs de IA",
    seoDescription:
      "LiteLLM unifica 100+ APIs de LLM bajo un solo formato. Balanceo de carga, fallbacks y control de costes para tu infraestructura IA.",
    readmeContent: null,
    author: "BerriAI",
    createdAt: new Date("2026-03-29"),
    updatedAt: new Date("2026-04-01"),
    publishedAt: new Date("2026-03-30"),
  },
  {
    id: 5,
    source: "github",
    sourceId: "immich-app/immich",
    url: "https://github.com/immich-app/immich",
    name: "Immich",
    description: "High-performance self-hosted photo and video management.",
    summaryEs:
      "La alternativa self-hosted a Google Photos que realmente funciona. Immich ofrece reconocimiento facial, búsqueda por IA, gestión de álbumes, y una app móvil nativa que sincroniza automáticamente. Rendimiento excepcional incluso con cientos de miles de fotos.",
    categoryId: 3,
    tags: ["fotos", "self-hosted", "privacidad", "ia", "multimedia"],
    difficulty: "medio",
    interestScore: 89,
    trendingVelocity: 3100,
    stars: 65000,
    forks: 4200,
    lastCommit: new Date("2026-04-01"),
    language: "TypeScript",
    isOssAlternative: true,
    alternativeTo: "Google Photos",
    replicableWithCode: null,
    automatizableWithN8n: null,
    featuredImageUrl: null,
    thumbnailUrl: null,
    contentImages: [],
    status: "published",
    priority: "high",
    seoSlug: "immich-alternativa-google-photos",
    seoTitle: "Immich: Tu propio Google Photos privado con IA integrada",
    seoDescription:
      "Immich es la mejor alternativa self-hosted a Google Photos. Reconocimiento facial, búsqueda IA y app móvil incluida.",
    readmeContent: null,
    author: "immich-app",
    createdAt: new Date("2026-03-27"),
    updatedAt: new Date("2026-04-01"),
    publishedAt: new Date("2026-03-28"),
  },
  {
    id: 6,
    source: "github",
    sourceId: "lobehub/lobe-chat",
    url: "https://github.com/lobehub/lobe-chat",
    name: "LobeChat",
    description:
      "Modern-design ChatGPT/LLM UI framework with plugins, TTS, and multi-model support.",
    summaryEs:
      "Un framework de interfaz para chatbots con un diseño espectacular. Soporta múltiples modelos (OpenAI, Ollama, Claude), tiene sistema de plugins, text-to-speech, y una UX que supera al propio ChatGPT. Ideal para crear tu propia plataforma de chat IA con marca blanca.",
    categoryId: 1,
    tags: ["chatbot", "ui", "plugins", "ia", "diseño"],
    difficulty: "facil",
    interestScore: 85,
    trendingVelocity: 2800,
    stars: 52000,
    forks: 11000,
    lastCommit: new Date("2026-04-01"),
    language: "TypeScript",
    isOssAlternative: true,
    alternativeTo: "ChatGPT",
    replicableWithCode: null,
    automatizableWithN8n: null,
    featuredImageUrl: null,
    thumbnailUrl: null,
    contentImages: [],
    status: "published",
    priority: "medium",
    seoSlug: "lobechat-interfaz-ia-moderna",
    seoTitle: "LobeChat: La interfaz de chat IA más bonita del open source",
    seoDescription:
      "LobeChat ofrece una UI moderna para chatbots con soporte multi-modelo, plugins y TTS. Alternativa visual a ChatGPT.",
    readmeContent: null,
    author: "lobehub",
    createdAt: new Date("2026-03-26"),
    updatedAt: new Date("2026-04-01"),
    publishedAt: new Date("2026-03-27"),
  },
];

export const demoCategories = [
  { id: 1, name: "Inteligencia Artificial", slug: "inteligencia-artificial", icon: "brain", count: 45 },
  { id: 2, name: "DevTools", slug: "devtools", icon: "wrench", count: 32 },
  { id: 3, name: "Self-hosted", slug: "self-hosted", icon: "server", count: 28 },
  { id: 4, name: "Automatización", slug: "automatizacion", icon: "zap", count: 19 },
  { id: 5, name: "Seguridad", slug: "seguridad", icon: "shield", count: 15 },
  { id: 6, name: "Bases de datos", slug: "bases-de-datos", icon: "database", count: 12 },
  { id: 7, name: "Frontend", slug: "frontend", icon: "layout", count: 22 },
  { id: 8, name: "Productividad", slug: "productividad", icon: "rocket", count: 18 },
];
